In [4]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu'],
       'age':[32,45,19,90,],
       'city':['warangal','bangalore','hyderabad','karimnagar']}
details=pd.DataFrame(data)
print(details)

        Name  age        city
0    saritha   32    warangal
1  Annapurna   45   bangalore
2      binnu   19   hyderabad
3      laddu   90  karimnagar

In [7]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu'],
       'age':[32,45,19,90,],
       'city':['warangal','bangalore','hyderabad','karimnagar']}
details=pd.DataFrame(data)
print(details.shape)#to find size of column and row

(4, 3)

In [10]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu'],
       'age':[32,45,19,90,],
       'city':['warangal','bangalore','hyderabad','karimnagar']}
details=pd.DataFrame(data)
print(details.columns)

Index(['Name', 'age', 'city'], dtype='object')

In [11]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu'],
       'age':[32,45,19,90,],
       'city':['warangal','bangalore','hyderabad','karimnagar']}
details=pd.DataFrame(data)
print(details.index)

RangeIndex(start=0, stop=4, step=1)

In [15]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.head())#shows only top 5 records
print(details.tail())

        Name  age        city
0    saritha   32    warangal
1  Annapurna   45   bangalore
2      binnu   19   hyderabad
3      laddu   90  karimnagar
4      srinu   78   hyderabad
        Name  age        city
1  Annapurna   45   bangalore
2      binnu   19   hyderabad
3      laddu   90  karimnagar
4      srinu   78   hyderabad
5      madhu   45    kakinada

In [18]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.sample(4))#if want random rows

        Name  age       city
4      srinu   78  hyderabad
1  Annapurna   45  bangalore
2      binnu   19  hyderabad
5      madhu   45   kakinada

In [19]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.info())#gives info about record

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   age     6 non-null      int64
 2   city    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes
None

In [20]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.describe())

             age
count   6.000000
mean   51.500000
std    27.223152
min    19.000000
25%    35.250000
50%    45.000000
75%    69.750000
max    90.000000

In [25]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details['Name'])

0      saritha
1    Annapurna
2        binnu
3        laddu
4        srinu
5        madhu
Name: Name, dtype: object

In [30]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.loc[[1,3]])#to find row

        Name  age        city
1  Annapurna   45   bangalore
3      laddu   90  karimnagar

In [32]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','karimnagar','hyderabad','kakinada']}
details=pd.DataFrame(data)
print(details.iloc[0])

Name     saritha
age           32
city    warangal
Name: 0, dtype: object

In [61]:

details=pd.DataFrame(data)import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu','madhu'],
       'age':[32,45,19,90,78,45],
       'city':['warangal','bangalore','hyderabad','k
print((details[details.age<=75]),(details[details.age>=60]))

        Name  age       city
0    saritha   32   warangal
1  Annapurna   45  bangalore
2      binnu   19  hyderabad
5      madhu   45   kakinada     Name  age        city
3  laddu   90  karimnagar
4  srinu   78   hyderabad

In [66]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu'],
       'age':[32,45,19,90,78],
       'city':['warangal','bangalore','hyderabad','karimnagar','karimnagar']}
details=pd.DataFrame(data)
print((details[details.age<=75]))

        Name  age       city
0    saritha   32   warangal
1  Annapurna   45  bangalore
2      binnu   19  hyderabad

In [75]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu'],
       'age':[32,45,19,90,78],
       'city':['warangal','bangalore','hyderabad','karimnagar','karimnagar']}
details=pd.DataFrame(data)
details['grade']=['A','B','A+','C','A']
print(details)

        Name  age        city grade
0    saritha   32    warangal     A
1  Annapurna   45   bangalore     B
2      binnu   19   hyderabad    A+
3      laddu   90  karimnagar     C
4      srinu   78  karimnagar     A

In [86]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu'],
       'age':[32,45,19,90,78],
       'city':['warangal','bangalore','hyderabad','karimnagar','karimnagar']}
details=pd.DataFrame(data)
details['age']=details['age']+2
print(details)

        Name  age        city
0    saritha   34    warangal
1  Annapurna   47   bangalore
2      binnu   21   hyderabad
3      laddu   92  karimnagar
4      srinu   80  karimnagar

In [87]:
import pandas as pd
data={
      'Name':['saritha','Annapurna','binnu','laddu','srinu'],
       'age':[32,45,19,90,78],
       'city':['warangal','bangalore','hyderabad','karimnagar','karimnagar']}
details=pd.DataFrame(data)
print(details.isnull())

    Name    age   city
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [95]:
data=pd.DataFrame({
      'Name':['saru','Anu','bunny','lucky'],
       'ID':[20,45,19,23]})
print(data)

    Name  ID
0   saru  20
1    Anu  45
2  bunny  19
3  lucky  23

In [97]:
data2=pd.DataFrame({
    'ID':[1,2,3,4],
    'Name':['anu','binni','renny','denny']})
print(data2)

   ID   Name
0   1    anu
1   2  binni
2   3  renny
3   4  denny

In [12]:
import pandas as pd
data=pd.DataFrame({
      'Name':['saru','Anu','bunny'],
       'ID':[20,45,19]})
    
data2=pd.DataFrame({
    'marks':[87,94,86,45],
     'ID':[20,87,67,68]})

result=pd.merge(data,data2,on="ID",how="left")
print(result)

    Name  ID  marks
0   saru  20   87.0
1    Anu  45    NaN
2  bunny  19    NaN

In [9]:
pd.merge(data,data2,how="inner",on="ID")

    Name  ID  marks
0   saru  20     87
1    Anu  45     94
2  bunny  19     86
3  lucky  23     74

In [11]:
import pandas as pd
pd.merge(data,data2,on="ID",how="left")

    Name  ID  marks
0   saru  20    NaN
1    Anu  45    NaN
2  bunny  19    NaN

In [13]:
import pandas as pd
pd.merge(data,data2,on="ID",how="outer")

    Name  ID  marks
0  bunny  19    NaN
1   saru  20   87.0
2    Anu  45    NaN
3    NaN  67   86.0
4    NaN  68   45.0
5    NaN  87   94.0

In [14]:
import pandas as pd
pd.merge(data,data2,on="ID",how="right")

   Name  ID  marks
0  saru  20     87
1   NaN  87     94
2   NaN  67     86
3   NaN  68     45